// <auto-generated />
using System;
using Investment_Calc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investment_Calc.Data.Migrations
{
    [DbContext(typeof(InvestCalcContext))]
    partial class InvestCalcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Investment_Calc.Data.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CurrentValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("Depreciation")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EnterDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Expiration")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("SalvageValue")
                        .HasColumnType("REAL");

                    b.Property<double>("StartValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Investment_Calc.Data.Models.ContactForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isResolved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Investment_Calc.Data.Models.InvestmentCalc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CmpPerYr")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FutureValue")
                        .HasColumnType("REAL");

                    b.Property<double>("Interest")
                        .HasColumnType("REAL");

                    b.Property<double>("Principle")
                        .HasColumnType("REAL");

                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Years")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("Investment_Calc.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
